trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureAppName: 'edusyncbackend5011'
  projectPath: 'EduSync/EduSync.csproj'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
  displayName: 'Install .NET SDK'

- script: dotnet restore $(projectPath)
  displayName: 'Restore NuGet Packages'

- script: dotnet build $(projectPath) --configuration $(buildConfiguration) --no-restore
  displayName: 'Build Project'

- script: dotnet test EduSync.Tests/EduSync.Tests.csproj --no-build --verbosity normal
  displayName: 'Run Unit Tests'

- script: dotnet publish $(projectPath) -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) --no-build
  displayName: 'Publish Project'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'EduSyncAzureConnection' # Must match the name of your Azure DevOps service connection
    appType: 'webApp'
    appName: '$(azureAppName)'
    package: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Deploy to Azure App Service'
